### PR TITLE
Added doPost() function

### PR DESCRIPTION
**Pull request by huihanlhh**

### CODE REVIEW

**Comment by amuhammad135** [comment]
Everything looks good! Let me know when you complete the check for if a user is already registered and implement some test cases for the RegisterServlet!

**Review by amuhammad135 — APPROVED** [review]
Looks good!

**Comment by huihanlhh** [comment]
@amuhammad135 I have finished the rest of this task! Thanks for reviewing them!

**Review by amuhammad135 — COMMENTED** [review]
Everything looks great! Is there a check/test that an empty username is handled appropriately?

**Pull request merged**
